name: Fork 동기화

on:
  schedule:
    - cron: '*/6 * * * *'  # 6분마다 실행
  workflow_dispatch:     # 수동 실행도 가능

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout forked repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # personal token을 따로 사용할 경우 필요

      - name: Set up Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/DONGSUKA/first_test.git #원본 저장소 주소
          git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories --no-edit || echo "✅ 병합할 내용 없음"

      - name: Push to fork
        run: |
          git push origin main
