name: Fork 동기화

on:
  schedule:
    - cron: '*/6 * * * *'  # 6분 마다 실행
  workflow_dispatch:     # 수동 실행

permissions:
  contents: write  # push를 위해 write 권한 필요

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout forked repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # ✅ 인증 토큰 사용

      - name: Set up Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/DONGSUKA/first_test.git
          git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout main
          git merge upstream/main --no-edit || echo "✅ 병합할 변경사항 없음"

      - name: Push to fork
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin main
