name: Fork Sync with Upstream

on:
  schedule:
    - cron: '*/6 * * * *'  # 6분마다 동기화
  workflow_dispatch:        # 수동 실행도 허용

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fork repository
        uses: actions/checkout@v4

      - name: Set Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/DONGSUKA/first_test.git
          git fetch upstream

      - name: Merge upstream/main into fork/main
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories --no-edit || true

          # 병합 충돌 감지 및 해결
          if git ls-files -u | grep -q .; then
            echo "🔧 충돌 발생. README.md를 upstream 버전으로 덮어쓰기"
            git checkout --theirs README.md
            git add README.md
            git commit -m "🤖 README 충돌 자동 해결 (upstream 기준)"
          fi

      - name: Push changes to forked repo
        run: |
          git push origin main
