name: README에 성경구절 업데이트

on:
  schedule:
    - cron: "*/6 * * * *" # 6분 마다 업데이트
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-bible-verse:
    runs-on: ubuntu-latest

    steps:
      - name: 리포지토리 체크아웃
        uses: actions/checkout@v4

      - name: Python 설치
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: README.md용 성경 구절 생성
        run: |
          import pickle
          import random
          import datetime

          # 현재 시간 (한국 기준)
          now = datetime.datetime.now(datetime.timezone(datetime.timedelta(hours=9)))
          today = now.strftime("%Y-%m-%d %H:%M:%S KST")

          # Pickle에서 구절 불러오기
          with open(".github/bible_verses.pkl", "rb") as f:
              verses = pickle.load(f)

          verse = random.choice(verses)
          ref = verse["ref"]
          text = verse["verse"]

          # 삽입할 텍스트 구성
          new_content = f"""<!-- START_BIBLE_VERSE -->
📖 **{ref}**
> {text}

🕊️ _업데이트 시각: {today}_
<!-- END_BIBLE_VERSE -->"""

          # README.md 수정
          with open("README.md", "r", encoding="utf-8") as f:
              content = f.read()

          import re
          updated = re.sub(r"<!-- START_BIBLE_VERSE -->(.|\n)*?<!-- END_BIBLE_VERSE -->", new_content, content)

          with open("README.md", "w", encoding="utf-8") as f:
              f.write(updated)

        shell: python

      - name: Git 설정
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: 변경 사항 커밋 및 푸시
        run: |
          if [[ -z $(git status --porcelain README.md) ]]; then
            echo "변경 사항 없음"
          else
            git add README.md
            git commit -m "📖 README 성경 구절 자동 업데이트"
            git push
          fi
